### PR TITLE
Add kafka algebras with fs2-kafka

### PR DESCRIPTION
**Pull request by vlovgr**

### CODE REVIEW

**Comment by MontyWest** [comment]
Sorry it's not much of a review, just checking:

So this adds algebras for the key methods of a kafka stream in the core and also adds a `fs2-kafka` implementation. The practical use of this over just `fs2-kafka` is that it creates the `ExecutionContext` for you?

**Comment by vlovgr** [comment]
Practical use is that we can create test implementations of `Fs2KafkaConsumer` and `Fs2KafkaProducer`, whereas the `KafkaConsumer` and `KafkaProducer` in fs2-kafka will become `sealed` in 0.17.0, so we'll have to define our own algebras. The `createDefaultFs2KafkaConsumerStream` function you're referring to is just for convenience, as we often seem to use the default `consumerExecutionContextStream`.

The `KafkaConsumer` and `KafkaProducer` in the core module are very generic, but also tailored to the shape of fs2-kafka, so their usefulness is quite limited. I think we should probably remove them.

**Comment by MontyWest** [comment]
So we would use the `Fs2KafkaConsumer` and `Fs2KafkaProducer` in our service algebras over the generic ones? Wouldn't this remove the ability to 'hide' the implementation?

Also, without the `KafkaConsumer` and `KafkaProducer` in the core module wouldn't we have to define our own algebras in each service in order to create test versions without having to depend on classes from `fs2.kafka` (e.g. `CommittableMessage`)?

(Not sure the above matters much though)

**Comment by vlovgr** [comment]
> So we would use the `Fs2KafkaConsumer` and `Fs2KafkaProducer` in our service algebras over the generic ones? Wouldn't this remove the ability to 'hide' the implementation?

Yes, the generic ones have been removed, and you wouldn't really use them directly anyway. All of these are just `trait`s without implementations, so you can have whatever logic behind those functions that you want.

> Also, without the `KafkaConsumer` and `KafkaProducer` in the core module wouldn't we have to define our own algebras in each service in order to create test versions without having to depend on classes from `fs2.kafka` (e.g. `CommittableMessage`)?

You just create test instances of `Fs2KafkaConsumer` and `Fs2KafkaProducer` (now renamed) in the services. It's fine to depend on classes from fs2-kafka, like `CommittableMessage`, because you can create custom instances of those for your test implementations.

**Comment by MontyWest** [comment]
Ah okay cool. Sorry this wasn't much of a review, but thanks for explaining 👍

**Pull request merged**
